openapi: 3.1.0
info:
  title: Game Server
  version: '1.0'
  contact:
    email: contact@braquage-royale.xyz
  description: Server to manage game
servers:
  - url: 'https://srv.braquage-royale.xyz'
    description: prod
paths:
  '/games/{gameId}/invite':
    parameters:
      - schema:
          type: string
        name: gameId
        in: path
        required: true
    post:
      summary: ''
      operationId: post-games-gameId-invite
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '503':
          description: Service Unavailable
      description: Send an invitation to selected players or email
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  emails:
                    type:
                      - string
                      - 'null'
                  player:
                    type:
                      - object
                      - 'null'
                    properties:
                      ref:
                        $ref: ''
        description: ''
      tags:
        - Invitation
components:
  schemas:
tags:
  - name: Game-server
  - name: Invitation
