name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Pre Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN_REPO }}"
          automatic_release_tag: "latest"
          prerelease: true
  release:
    name: Release
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        run: |
          echo "done!"
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN_REPO }}"
          prerelease: false
  deploy:
    name: Deploy
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
