name: Deploy to Google

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ master ]
jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
    - name: release-please-action
      # You may pin to the exact commit or the version.
      # uses: google-github-actions/release-please-action@f56f8adcf466bbca4a93bdb614426bde63492f6f
      uses: google-github-actions/release-please-action@v2.19.2
      with:
        token: ${{ secrets.FIREBASE_TOKEN }}
        default-branch: master
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./functions
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install libraries
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: install firebase
        run: npm i firebase-tools -g
      - name: deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
