name: Release & Deploy

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ master ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: release-please-action
      uses: google-github-actions/release-please-action@v2.19.2
      with:
        token: ${{ secrets.TOKEN_REPO }}
        release-type: node
        default-branch: master
  merge:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: auto-pull-request-merge
      # You may pin to the exact commit or the version.
      # uses: KeisukeYamashita/auto-pull-request-merge@f16c055886db96657279e79ce5ba7979738ac1e8
      uses: KeisukeYamashita/auto-pull-request-merge@v1
      with:
        # Comma seperated labes that target pull request should have
        labels: "autorelease: pending"
        token: ${{ secrets.TOKEN_REPO }}
        timeoutSeconds: 300
  build:
    needs: merge
    runs-on: ubuntu-latest
    env:
      working-directory: ./functions
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install libraries
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: install firebase
        run: npm i firebase-tools -g
      - name: deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
